# motel database config
#
# Fedora Install Instructions:
#   sudo yum install ruby-postgres postgresql-server
#   sudo /sbin/service postgresql initdb
#   sudo /sbin/service postgresql start
#   sudo su - postgres
#   createdb motel
#   $   psql motel
#   $-# CREATE USER motel WITH PASSWORD 'motel';
#   $-# GRANT ALL PRIVILEGES ON DATABASE motel to motel;
#   $-# CREATE DATABASE motel_test;
#   $-# GRANT ALL PRIVILEGES ON DATABASE motel_test to motel;
#   $-# CREATE DATABASE motel_development;
#   $-# GRANT ALL PRIVILEGES ON DATABASE motel_development to motel;
#   $-# \q
#   $   exit

production:
  adapter: postgresql
  database: motel
  username: motel
  password: motel
  host: localhost
  pool: 20

development:
  adapter: postgresql
  database: motel_development
  username: motel
  password: motel
  host: localhost
  pool: 20

test:
  adapter: postgresql
  database: motel_test
  username: motel
  password: motel
  host: localhost
  pool: 20
